In [3]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
# Tells which GPU is available to me
if torch.cuda.is_available():
  print('GPU is available')
  print(f'Using GPU : {torch.cuda.get_device_name(0)}')
else:
  print('GPU not available. Using CPU')

GPU not available. Using CPU


In [4]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f'Using GPU : {torch.cuda.get_device_name(0)}')
else:
  print('GPU not available. Using CPU')

GPU is available
Using GPU : Tesla T4


**Creating a Tensor**

In [5]:
#using empty : this allocates memory the value already existing in the memory at the position represent that.

torch.empty(2,3)

tensor([[-1.2754e+07,  4.5863e-41, -1.2754e+07],
        [ 4.5863e-41,  0.0000e+00,  0.0000e+00]])

In [6]:
# Check type
a = torch.empty(2,3)
type(a)

torch.Tensor

In [8]:
#using zeroes
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# using ones
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
# using rand
torch.rand(2,4)

tensor([[0.7653, 0.4682, 0.0884, 0.6115],
        [0.5415, 0.1820, 0.5865, 0.2844]])

In [11]:
#use of seed to make the values of rand permanent
torch.manual_seed(100)
torch.rand(2,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [18]:
# using tensor
b = torch.tensor([[1,2,3],[4,5,6]])
print(b)
print(type(b))
print(b.shape)



tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
torch.Size([2, 3])


In [19]:
# Other ways
# Arange
print("using arange : ",torch.arange(0,10))

# using linspace
print("using linspace : ",torch.linspace(0,10,10))

# using eye
print('using eye : ',torch.eye(5))

#using full
print('using full : ',torch.full((3,3),5))


using arange :  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace :  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [23]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape)

torch.Size([3, 3])


In [24]:
torch.empty_like(x)

tensor([[              0,             145,      1168396528],
        [140573394771296,      4294967306,             113],
        [140573394771168, 140573394771168,               0]])

In [26]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [27]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

**Tensor Data Type**

In [28]:
x.dtype

torch.int64

In [29]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
torch.tensor([1,2,3],dtype =torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [31]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [32]:
torch.rand_like(x,dtype =torch.float32)

tensor([[0.2080, 0.1180, 0.1217],
        [0.7356, 0.7118, 0.7876],
        [0.4183, 0.9014, 0.9969]])

**Mathematical operations**

In [34]:
# Addition
a = torch.tensor([[1,2],[2,2]])
b = torch.tensor([[3,4],[4,4]])
print(a+b)

tensor([[4, 6],
        [6, 6]])


In [36]:
# Addition
print(a+2)
print(b+3)

tensor([[3, 4],
        [4, 4]])
tensor([[6, 7],
        [7, 7]])


In [38]:
# Multiplication
print(a*b)
print(2*a)
print(3*b)

tensor([[3, 8],
        [8, 8]])
tensor([[2, 4],
        [4, 4]])
tensor([[ 9, 12],
        [12, 12]])


In [40]:
# Matrix Multiplication

print(torch.matmul(a,b))

tensor([[11, 12],
        [14, 16]])


In [42]:
print(a**b)
print(a%b)

tensor([[ 1, 16],
        [16, 16]])
tensor([[1, 2],
        [2, 2]])


In [43]:
c = torch.tensor([1,-2,3,-4])
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [45]:
#negation
torch.neg(c)

tensor([-1,  2, -3,  4])

In [47]:
#round
d = torch.tensor([1.9,2.3,3.7,4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [48]:
#Ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [49]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [50]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**Reduction Operations**

In [51]:
e = torch.randint(size=(2,3),low =0,high=10)
e

tensor([[0, 4, 3],
        [8, 7, 4]])

In [52]:
print(torch.sum(e))
print(torch.sum(e,dim=0)) # along columns
print(torch.sum(e,dim=1))

tensor(26)
tensor([ 8, 11,  7])
tensor([ 7, 19])


In [62]:
print(torch.mean(d)) # only for float dtypes

#mean along col
print(f"Mean : {torch.mean(d,dim=0)}")

#Median
print(f"Median : {torch.median(d)}")

tensor(3.0750)
Mean : 3.0749998092651367
Median : 2.299999952316284


In [63]:
#Max and min
print(f"Max : {torch.max(d)}")
print(f"Min : {torch.min(d)}")

Max : 4.400000095367432
Min : 1.899999976158142


In [64]:
# product
print(f"Product : {torch.prod(d)}")
#standard deviation
print(f" SD  : {torch.std(d)}")

#variance
print(f"Variance : {torch.var(d)}")

#argmax
print(f"Argmax : {torch.argmax(d)}")

Product : 71.14360809326172
 SD  : 1.172959327697754
Variance : 1.375833511352539
Argmax : 3


**Matrix multiplication**

In [65]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[6, 0, 1],
        [9, 9, 8]])
tensor([[0, 7],
        [0, 0],
        [9, 5]])


In [67]:
print(f" Multiplication : \n{torch.matmul(f,g)}")

 Multiplication : 
tensor([[  9,  47],
        [ 72, 103]])


In [71]:
# Dot product # only for 1D for more dim use matmul()
p = torch.tensor([1,2])
q = torch.tensor([1,1])
print(f"Dot product : {torch.dot(p,q)}")

Dot product : 3


In [72]:
torch.transpose(f,0,1)

tensor([[6, 9],
        [0, 9],
        [1, 8]])

In [73]:
torch.transpose(f,1,0)

tensor([[6, 9],
        [0, 9],
        [1, 8]])

In [78]:
# Determinant
# torch.det() requires a floating-point or complex tensor. If you use integers, PyTorch may raise an error depending on the version.
a1 = torch.tensor([[1.,2.,3.],[3.,4.,6.],[2.,5.,8.]])
torch.det(a1)

tensor(-1.0000)

In [79]:
torch.inverse(a1)

tensor([[-2.0000,  1.0000,  0.0000],
        [12.0000, -2.0000, -3.0000],
        [-7.0000,  1.0000,  2.0000]])

**Comparison Operations**

In [80]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[7, 3, 9],
        [4, 0, 5]])
tensor([[7, 5, 9],
        [9, 7, 5]])


In [81]:
# greater than
i > j
i<j
i == j
i>= j
i <= j

tensor([[True, True, True],
        [True, True, True]])

**Special Functions**

In [91]:
k = torch.randint(size =(2,3),low=0,high=10)

print(f"log : {torch.log(k)})")
print('\n')
print(f"exp : {torch.exp(k)})")
print('\n')
print(f"sqrt : {torch.sqrt(k)})")
print('\n')
print(f"sigmoid : {torch.sigmoid(k)})")
print('\n')
print(f"relu : {torch.relu(k)})")

log : tensor([[1.7918, 0.0000, 1.3863],
        [1.6094, 1.7918, 2.1972]]))


exp : tensor([[4.0343e+02, 2.7183e+00, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 8.1031e+03]]))


sqrt : tensor([[2.4495, 1.0000, 2.0000],
        [2.2361, 2.4495, 3.0000]]))


sigmoid : tensor([[0.9975, 0.7311, 0.9820],
        [0.9933, 0.9975, 0.9999]]))


relu : tensor([[6, 1, 4],
        [5, 6, 9]]))


**Inplace Operations**

In [92]:
m = torch.rand(2,3)
n = torch.rand(2,3)
m.add_(n)

tensor([[1.3610, 1.6774, 1.5705],
        [0.5734, 1.4325, 0.9792]])

In [93]:
torch.relu(m)

tensor([[1.3610, 1.6774, 1.5705],
        [0.5734, 1.4325, 0.9792]])

In [94]:
m.relu_() #inplace operation permanent to original variable

tensor([[1.3610, 1.6774, 1.5705],
        [0.5734, 1.4325, 0.9792]])

In [96]:
# Copying a Tensor
a = torch.rand(2,3)
a

tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])

In [97]:
id(a) # location of operator in memory

140567481059200

In [99]:
b = a.clone()
b

tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])

In [101]:
a[0][0] = 10
print(a)
print(b)

tensor([[10.0000,  0.5057,  0.5688],
        [ 0.0634,  0.8993,  0.2732]])
tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])


#**Tensor Operations on GPU**

In [102]:
torch.cuda.is_available() #check for GPU

True

In [105]:
device = torch.device('cuda') # stores GPU device
device

device(type='cuda')

In [106]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [107]:
# movind an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.3397, 0.1879, 0.5534],
        [0.2682, 0.9556, 0.9761]])

In [109]:
b = a.to(device)
b

tensor([[0.3397, 0.1879, 0.5534],
        [0.2682, 0.9556, 0.9761]], device='cuda:0')

In [110]:
b+5 # operation performed on GPU

tensor([[5.3397, 5.1879, 5.5534],
        [5.2682, 5.9556, 5.9761]], device='cuda:0')

In [111]:
import time

# Define the size of the matrices
size = 10000

# Create random matrices on CPU
mat_cpu1 = torch.randn(size,size)
mat_cpu2 = torch.randn(size,size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(mat_cpu1,mat_cpu2) # Matrix Multiplication
cpu_time = time.time() - start_time

print(f"Time Taken on CPU : {cpu_time:4f} seconds")

# Move matrices on GPU
mat_GPU1 = mat_cpu1.to('cuda')
mat_GPU2 = mat_cpu2.to('cuda')

#Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(mat_GPU1,mat_GPU2)
torch.cuda.synchronize() # Ensure all GPU operations are complete
GPU_time = time.time() - start_time

print(f"Time on GPU : {GPU_time:4f} seconds")

#Compare results
print("\n Speedup (CPU time/GPU time ): ",cpu_time/GPU_time)


Time Taken on CPU : 16.702138 seconds
Time on GPU : 0.740154 seconds

 Speedup (CPU time/GPU time ):  22.565752768944527


**Reshaping Tensors**

In [112]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [113]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [114]:
#Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [115]:
b = torch.rand(2,3,4)
b

tensor([[[0.8801, 0.4203, 0.8186, 0.0463],
         [0.7306, 0.2009, 0.3265, 0.6684],
         [0.3509, 0.7772, 0.2353, 0.4301]],

        [[0.4385, 0.7375, 0.5494, 0.7109],
         [0.0148, 0.7262, 0.4660, 0.0610],
         [0.7108, 0.5127, 0.8211, 0.1323]]])

In [116]:
#permute
b.permute(2,0,1) # indexing of (2,3,4)

tensor([[[0.8801, 0.7306, 0.3509],
         [0.4385, 0.0148, 0.7108]],

        [[0.4203, 0.2009, 0.7772],
         [0.7375, 0.7262, 0.5127]],

        [[0.8186, 0.3265, 0.2353],
         [0.5494, 0.4660, 0.8211]],

        [[0.0463, 0.6684, 0.4301],
         [0.7109, 0.0610, 0.1323]]])

In [117]:
# unsqueeze
c = torch.rand(226,226,3) #image size
c.unsqueeze(0).shape


torch.Size([1, 226, 226, 3])

In [118]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [122]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0)

tensor([0.8759, 0.6815, 0.7504, 0.5928, 0.2658, 0.8542, 0.1179, 0.4115, 0.5468,
        0.5968, 0.0434, 0.6032, 0.7566, 0.5052, 0.5691, 0.3058, 0.5725, 0.3627,
        0.1430, 0.7469])

**Numpy and Pytorch**

In [123]:
import numpy as np

In [124]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [125]:
b = a.numpy()

In [127]:
type(b)

numpy.ndarray

In [128]:
c  = np.array([1,2,3])
torch.from_numpy(c)

tensor([1, 2, 3])